#ifndef HTTP_DISPATCHER_H
#define HTTP_DISPATCHER_H

#include <Arduino.h>
#include <vector>
#include <algorithm>
#include <MicroFunction.h>
#include "HttpRequest.h"
#include "HttpResponse.h"
#include "ResponseBuffer.h"

class HttpDispatcher {
public:
    using Handler = microcore::MicroFunction<HttpResponse(HttpRequest&, ResponseBuffer&), 8>;

    struct RouteHandle {
        int id;
        bool valid() const { return id >= 0; }
        static RouteHandle invalid() { return {-1}; }
    };

    HttpDispatcher() = default;

    // Route registration (patterns and methods are always string literals)
    RouteHandle on(const char* method, const char* pattern, Handler handler, int priority = 0);
    RouteHandle onGet(const char* pattern, Handler handler, int priority = 0);
    RouteHandle onPost(const char* pattern, Handler handler, int priority = 0);
    RouteHandle onPut(const char* pattern, Handler handler, int priority = 0);
    RouteHandle onDelete(const char* pattern, Handler handler, int priority = 0);

    // Route with ETag (checked before handler is called)
    RouteHandle onGet(const char* pattern, Handler handler, const char* etag, int priority = 0);

    // Serve a static Resource (generated by compress-resources)
    // ETag is the global firmware hash — set via setEtag() once at startup
    RouteHandle resource(const char* pattern, const Resource& res);

    // Override global ETag (defaults to BuildInfo::firmwareHash())
    void setEtag(const char* etag) { _globalEtag = etag; }

    // Void handler overloads
    template<typename F>
    auto onGet(const char* pattern, F handler, int priority = 0)
        -> std::enable_if_t<std::is_void_v<decltype(handler(std::declval<HttpRequest&>(), std::declval<ResponseBuffer&>()))>, RouteHandle>
    { return on("GET", pattern, [handler](HttpRequest& req, ResponseBuffer& buf) -> HttpResponse { handler(req, buf); return HttpResponse::ok(); }, priority); }

    template<typename F>
    auto onPost(const char* pattern, F handler, int priority = 0)
        -> std::enable_if_t<std::is_void_v<decltype(handler(std::declval<HttpRequest&>(), std::declval<ResponseBuffer&>()))>, RouteHandle>
    { return on("POST", pattern, [handler](HttpRequest& req, ResponseBuffer& buf) -> HttpResponse { handler(req, buf); return HttpResponse::ok(); }, priority); }

    // Remove routes
    bool off(RouteHandle handle);
    bool off(const char* method, const char* pattern);

    // Dispatch request
    HttpResponse dispatch(HttpRequest& req, ResponseBuffer& buf);

    // 404 handler
    void onNotFound(Handler handler);

    // Config
    void setWarnOnCollision(bool warn) { _warnOnCollision = warn; }
    size_t routeCount() const { return _routes.size(); }
    void clear();

private:
    struct Route {
        int id;
        const char* method;
        const char* pattern;
        Handler handler;
        int priority;
        const char* etag = nullptr;
    };

    std::vector<Route> _routes;
    int _nextId = 0;
    bool _warnOnCollision = true;
    bool _needsSort = false;
    Handler _notFoundHandler;
    const char* _globalEtag = nullptr;  // Lazy-initialized to BuildInfo::firmwareHash()
    const char* globalEtag();

    RouteHandle addRoute(const char* method, const char* pattern, Handler handler, int priority, const char* etag = nullptr);
    void sortIfNeeded();
    bool checkCollision(const char* method, const char* pattern, int priority);
    static bool matchEtag(StringView clientEtag, const char* routeEtag);
};

#endif
